### ISSUE TITLE
Module load errors in front if an application is installed but its directory is missing

### ISSUE THREAD

**Issue by jay3** [novius-os/core#22] opened 2013-02-20 14:39 UTC
If an application is installed but its directory is not present in local/applications, errors occurs in the front part, even if this application is not used in the front.
Example: Module 'noviusos_appwizard' could not be found

**Comment by felixgilles** [comment] 2013-02-21 10:08
This commit (00d54f5557bc4876b39f28de6612b397c89864f9) solves the bug.
But I don't close it, we have the same regression in back-office.
The problem is the translation of metadata application.

**Comment by Savageman** [comment] 2013-08-06 09:33
I'm closing this now, since it has been fixed in Chiba 2.
13e9c7d48150a6d067b1c148423359087e81b7a6

**Closed as completed by Savageman** 2013-08-06 09:33 UTC
